### ISSUE TITLE
Can you only use this within node.js?

### ISSUE THREAD

**Issue by zedzedalpha** [dfellis/queue-flow#4]
I'm trying to play around with queue-flow on jsfiddle.net and just trying one of the examples it's spitting out the error: 

ReferenceError: process is not defined
[Break On This Error]   

if(!process || !process.nextTick) {

queue-flow.js (line 27)

TypeError: event.namespace.split is not a function
[Break On This Error]   

q('linearize')

/zedzedalpha...8/show/ (line 66)

TypeError: q is not a function
[Break On This Error]   

q('linearize')

**Comment by dfellis** [comment]
To be honest, the last time I tried using `queue-flow` in the browser was in the 0.3.x days, but I thought I had a test in my unit tests to try and simulate running it in the browser, but apparently it doesn't work as well as expected. With your error message I can see why that happened. I will fix this regression ASAP.

**Comment by dfellis** [comment]
Fixed. Grab the latest version or `npm install queue-flow@0.5.30`. :)

Please close the issue if it's working for you, too. I tested this with my browsers, but they may be different from your's.

**Comment by zedzedalpha** [comment]
That seems to have fixed it and the examples are working great in jsfiddle.

Thanks!

**Comment by mattguo** [comment]
Reproduced with latest git code (0.6.5)

Chrome throws "Uncaught ReferenceError: q is not defined"

While the same code can work with 0.5.30 build.

my HTML:

``` html
<script type="text/javascript" src="queue-flow.min.js"></script>
<script type="text/javascript">
q([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    .map(function(val) {
        return val*2;
    })
    .reduce(function(cum, cur) {
        return cum + cur;
    }, function(result) {
        alert(result);
    }, 0);
</script>
```

**Comment by mattguo** [comment]
I tried to browserify the script with -r
`browserify -r queue-flow >q.js`

Then the testing HTML worked, with explicit require (alerted 110)

``` html
<script type="text/javascript" src="q.js"></script>
<script type="text/javascript">
var q = require('queue-flow');

q([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    .map(function(val) {
        return val*2;
    })
    .reduce(function(cum, cur) {
        return cum + cur;
    }, function(result) {
        alert(result);
    }, 0);
</script>
```

**Comment by dfellis** [comment]
You're right, and I don't want to force browser users to use CommonJS-style `require`s even if I think it's the best way to manage modules.

I think I have a quick fix for this, and will publish it as 0.6.6 after you confirm it.

**Comment by mattguo** [comment]
I can verify that eea74ae fixed the issue.
Thanks!

**Comment by dfellis** [comment]
Just for posterity's sake, this is the page I used to verify it locally before finishing that commit.

``` html
<html>
    <head>
        <title>Test</title>
        <script src="./queue-flow.min.js"></script>
        <script>
            q([1, 2, 3])
                .map(function(x) { return x*2 })
                .toArray(function(arr) {
                    alert(arr);
                });
        </script>
    </head>
    <body></body>
</html>
```
